### ISSUE TITLE
Whats the exact value of opt.dropout

### ISSUE THREAD

**Issue by pz0910** [Fourure/GridNet#3]
Hi, I can not find the value of dropout in the codes released.
Is it set to 0.5?
Could you please help me out?

**Comment by pz0910** [comment]
Lucky. I find it in './parameters.lua'. It is set to 0.1. Dose that equal to  rij in the paper?

**Comment by Fourure** [comment]
Hi,
Yes the value is set to 0.1 and it corresponds to the probability to "drop" the activation. So in the paper, it corresponds to 1-p of ri,j = Bernoulli(p) (in the paper, p is expressed as the probability to "keep" the activation).
With a value too high there is a non-negligible probability to "cut" the information flow.
There is still a lot of improvements to do with the dropout. For example, lower streams could have a higher probability to keep the activation (forcing the network to use more the high level semantic streams rather than the high resolution ones).

**Comment by pz0910** [comment]
> Hi,
> Yes the value is set to 0.1 and it corresponds to the probability to "drop" the activation. So in the paper, it corresponds to 1-p of ri,j = Bernoulli(p) (in the paper, p is expressed as the probability to "keep" the activation).
> With a value too high there is a non-negligible probability to "cut" the information flow.
> There is still a lot of improvements to do with the dropout. For example, lower streams could have a higher probability to keep the activation (forcing the network to use more the high level semantic streams rather than the high resolution ones).

Thanks for your reply！

**Comment by Fourure** [comment]
You're welcome. If you need any help, don't hesitate to contact me again.
